# Generated by Django 4.2.6 on 2023-10-09 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_turma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id_aluno', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('data_de_nascimento', models.DateField()),
                ('endereco', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id_professor', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=15)),
            ],
        ),
    ]
